Feature/ball slingshot
RoboCupULaval/UI-Debug pull request #121
Opened 2018-11-02 19:42 UTC by SimLemay

Usage: 
Click on the FieldView to focus the widget
Hold Ctrl to enter slingshot mode
Hold Shift if you want to lock the slingshot distance (you can then use your cursor to aim at the target)
Click to on the target to throw the ball

2018-11-03 02:09 UTC, PhiBabin requested changes

2018-11-03 02:09 UTC, PhiBabin commented on View/FieldView.py
> +        return theta
ouin, on devrait probablement rajouter `Position` dans l'UI, c'est un peu plate d'avoir une duplication de code, mais en même temps je pense que cela serait plus clean,

2018-11-03 02:09 UTC, PhiBabin commented on View/FieldView.py
> +        else:
Tu peux utilisez `math.atan2()` pour faire cela.

2018-11-15 02:02 UTC, TwistedSim reviewed
Position in UI ? Is it finally happening ? wouuhou

2018-11-15 02:14 UTC, PhiBabin approved these changes

2018-11-15 02:16 UTC, SimLemay commented on View/FieldView.py
> +        else:
*******atan2(y, x) !

2018-11-15 02:33 UTC, merged